name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Adjust to the required .NET version

      - name: Restore dependencies
        run: dotnet restore DotNetTestingFramework/MyProject.sln

      - name: Build the solution
        run: dotnet build DotNetTestingFramework/MyProject.sln --no-restore --configuration Debug

      - name: Run tests
        run: dotnet test DotNetTestingFramework/MyProject.sln --no-build --configuration Debug
