name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Specify the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore MyProject.sln
        working-directory: DotNetTestingFramework

      - name: Build the solution
        run: dotnet build MyProject.sln --no-restore --configuration Debug
        working-directory: DotNetTestingFramework

      - name: Run tests
        run: dotnet test MyProject.sln --no-build --configuration Debug
        working-directory: DotNetTestingFramework
