# .github/workflows/ci.yml
name: .NET Selenium Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build project
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run tests
      - name: Run Selenium tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=TestResults.trx"

      # Step 6: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: '**/TestResults.trx'
